name: Deploy Golang API

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y awscli

      - name: Build Golang Lambda
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Upload to S3
        run: |
          aws s3 cp deployment.zip s3://${{ secrets.S3_BUCKET }}/deployment.zip

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --stack-name dharti-golang-api-deployment-stack \
            --template-file template.yaml \
            --capabilities CAPABILITY_NAMED_IAM
