name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Install dependencies
        run: go mod tidy

      - name: Build binary
        run: |
          GOOS=linux GOARCH=amd64 go build -o bootstrap main.go
          chmod +x bootstrap
          zip deployment.zip bootstrap

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload to S3
        run: aws s3 cp deployment.zip s3://${{ secrets.S3_BUCKET_NAME }}/lambda/go-lambda.zip

      - name: Deploy CloudFormation stack
        run: |
          aws cloudformation validate-template --template-body file://deployment.yml 
          aws cloudformation deploy \
            --template-file deployment.yml \
            --stack-name dharti-golang-api-deployment-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides \
              S3BucketName=${{ secrets.S3_BUCKET_NAME }} \
              LambdaFunctionName=DevopsGolangLambda \
              CustomDomainName=${{ secrets.CUSTOM_DOMAIN }} \
              CertificateArn=${{ secrets.CERTIFICATE_ARN }} \
              HostedZoneId=${{ secrets.HOSTED_ZONE_ID }}
